language: java
script:
    - mvn clean
    - mvn compile
    - mvn assembly:single
    - java -jar server.jar &
    - mvn test
deploy:
  provider: heroku
  api_key:
    secure: 8ea990d5-307f-45eb-b338-56b932d453db
  app: simpleservl
